name: flutter_hostname
description: An example to get and set the system hostname on Linux.
publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  dbus: ^0.6.3
  flutter:
    sdk: flutter
  provider: ^6.0.0
  yaru: ^0.1.3

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
